version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bank_db
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
    ports:
      - "5432:5432"
    volumes:
      - bank_db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bank_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank
      SPRING_DATASOURCE_USERNAME: bankuser
      SPRING_DATASOURCE_PASSWORD: bankpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      JWT_SECRET: youCannotHackMe100
      JWT_EXPIRATION: 86400000 #24 часа поставил
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["./mvnw", "spring-boot:run"]

volumes:
  bank_db_data:
