server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankdb}
    username: ${SPRING_DATASOURCE_USERNAME:bank}
    password: ${SPRING_DATASOURCE_PASSWORD:bank_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  liquibase:
    change-log: classpath:db/migration/changelog-master.yaml

logging:
  level:
    root: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

jwt:
  secret: ${JWT_SECRET:change-me-in-prod}
  expiration-ms: ${JWT_EXPIRATION:86400000} # 24 часа
